Repository LocalStoryMap/Oz_Frontend, pull requests merged in 2025-05, with the labels that each got.

#15 🎨 style: Panda CSS 기반 프리셋 및 글로벌 스타일 시스템 설정
  .eslintrc.json
  .gitattributes
  .gitignore
  panda.config.ts
  src/app/layout.tsx
  src/app/testPage/page.tsx
  src/components/ui/common/buttons/Button.tsx
  src/components/ui/common/buttons/buttonStyle.ts
  src/types/responsive.ts
Labels: 📄 docs, 💄 Design

#14 ✨Feat: SVG 자산 컴포넌트화 및 전체 적용
  src/app/icon-preview/page.tsx
  src/components/icons/business/OpenBookIcon.tsx
  src/components/icons/business/PenIcon.tsx
  src/components/icons/business/TravelIcon.tsx
  src/components/icons/business/UserIcon.tsx
  src/components/icons/business/VersionIcon.tsx
  src/components/icons/business/index.ts
  src/components/icons/food/CoffeeCupIcon.tsx
  src/components/icons/food/ForkSpoonIcon.tsx
  src/components/icons/food/index.ts
  src/components/icons/iconProps.ts
  src/components/icons/index.ts
  src/components/icons/location/GpsLocationIcon.tsx
  src/components/icons/location/HomeMarkerIcon.tsx
  src/components/icons/location/LocationIcon.tsx
  src/components/icons/location/MapLocationIcon.tsx
  src/components/icons/location/MapMarkerIcon.tsx
  src/components/icons/location/index.ts
  src/components/icons/navigation/BackIcon.tsx
  src/components/icons/navigation/ChevronRightIcon.tsx
  src/components/icons/navigation/EllipsisIcon.tsx
  src/components/icons/navigation/LogOutIcon.tsx
  src/components/icons/navigation/SearchIcon.tsx
  src/components/icons/navigation/SettingsIcon.tsx
  src/components/icons/navigation/index.ts
  src/components/icons/shared/LogoIcon.tsx
  src/components/icons/shared/MenuIcon.tsx
  src/components/icons/shared/index.ts
  src/components/icons/time/CalendarIcon.tsx
  src/components/icons/time/ClockIcon.tsx
  src/components/icons/time/index.ts
  src/components/icons/ui/BookmarkIcon.tsx
  src/components/icons/ui/CheckIcon.tsx
  src/components/icons/ui/CommentsIcon.tsx
  src/components/icons/ui/DangerIcon.tsx
  src/components/icons/ui/HeartIcon.tsx
  src/components/icons/ui/ImgIcon.tsx
  src/components/icons/ui/StarIcon.tsx
  src/components/icons/ui/ThemeIcon.tsx
  src/components/icons/ui/index.ts
Labels: 📄 docs, ✨ feature, ♻️ refactor

#19 ✨ feat: 헤더 컴포넌트 구현
  src/app/layout.tsx
  src/app/page.tsx
  src/components/icons/shared/CloseIcon.tsx
  src/components/icons/shared/LogoIcon.tsx
  src/components/icons/shared/index.ts
  src/components/layouts/Header.tsx
  src/components/layouts/header.recipe.ts
  src/constants/headerMenu.ts
Labels: ✨ feature, 💄 Design, :art: structure

#22 ✨Feat: PageHeader 컴포넌트 구현
  src/components/ui/common/pageHeader/PageHeader.tsx
  src/components/ui/common/pageHeader/pageHeader.recipe.ts
Labels: 📄 docs, ✨ feature, 💄 Design
