Repository LocalStoryMap/Oz_Frontend, pull requests merged in 2025-06, with the labels that each got.

#27 ✨ Feat: 공통 카드 컴포넌트 구현
  .eslintrc.json
  public/images/default-thumbnail.png
  public/images/default-userImage.png
  public/images/story-sample.png
  src/app/card/page.tsx
  src/app/layout.tsx
  src/components/icons/location/LocationIcon.tsx
  src/components/icons/ui/StarIcon.tsx
  src/components/ui/common/cards/BenefitCard.tsx
  src/components/ui/common/cards/SquareCard.tsx
  src/components/ui/common/cards/StoryCard.tsx
  src/components/ui/common/cards/WideCard.tsx
  src/components/ui/common/cards/WideCardContent.tsx
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/common/ratings/StarRating.tsx
Labels: ✨ feature, 💄 design

#29 ✨ Feat: 공통 모달 컴포넌트 구현
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/common/modals/Modal.tsx
  src/components/ui/common/modals/modal.recipe.ts
  src/hooks/useClickOutside.ts
  src/hooks/useHooks.ts
  src/store/useAuthStore.ts
  src/store/useModalStore.ts
Labels: ✨ feature, 💄 design

#31 ✨ Feat: 게시판페이지 구현
  public/images/mainStory.png
  src/app/story/page.tsx
  src/components/story/StoryListPage.tsx
  src/components/story/sections/StoryHeroSection.tsx
  src/components/story/sections/StoryListSection.tsx
  src/components/story/sections/StorySearchSection.tsx
  src/components/story/sections/story.recipe.ts
  src/components/story/utils/isMatchedByKeywordAndRegion.ts
  src/components/story/utils/normalizeText.ts
  src/mocks/mockStoryList.ts
Labels: ✨ feature, 💄 design

#32 ✨ Feat: 지도 홈 페이지 구현
  src/app/map/layout.tsx
  src/app/map/page.tsx
  src/components/icons/food/CoffeeCupIcon.tsx
  src/components/icons/location/GpsLocationIcon.tsx
  src/components/icons/location/MapLocationIcon.tsx
  src/components/map/MapTabs.tsx
  src/components/map/map.recipe.ts
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/common/pageHeader/PageHeader.tsx
  src/components/ui/common/pageHeader/pageHeader.recipe.ts
  src/constants/config.ts
  src/constants/headerMenu.ts
  src/constants/map.ts
Labels: ✨ feature, 💄 design

#43 :memo: memo: #42 코드 리뷰 Ai yaml 설정 파일 추가
  .coderabbit.yaml
Labels: 📄 docs

#41 ♻️ Refactor: cva 스타일 객체 변수명 대문자 → 소문자 일괄 변경
  src/components/story/sections/StoryHeroSection.tsx
  src/components/story/sections/StorySearchSection.tsx
  src/components/story/sections/story.recipe.ts
  src/constants/headerMenu.ts
Labels: ✨ feature, ♻️ refactor

#48 💄 Design: favicon 변경
  src/app/favicon.ico
Labels: 💄 design

#49 ✨ Feat: 지도 상세 페이지 구현
  src/app/map/[id]/page.tsx
  src/components/map/MapDetailStory.tsx
  src/components/map/MapTabs.tsx
  src/components/map/map.recipe.ts
  src/components/ui/common/cards/SquareCard.tsx
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/common/modals/Modal.tsx
  src/components/ui/common/modals/modal.recipe.ts
  src/mocks/mapDetail.ts
Labels: ✨ feature, 💄 design

#39 ✨ Feat: 게시판 상세 페이지 구현
  src/app/story/[storyId]/page.tsx
  src/components/story/detail/UserHeaderInfo.tsx
  src/components/story/detail/comment.recipe.ts
  src/components/story/detail/comment/ActionButtons.tsx
  src/components/story/detail/comment/CommentCard.tsx
  src/components/story/detail/comment/CommentContent.tsx
  src/components/story/detail/comment/CommentInputBox.tsx
  src/components/story/detail/comment/ReplyInput.tsx
  src/components/story/detail/post/PostReactionButtons.tsx
  src/components/story/detail/sections/StoryDetailCommentCard.tsx
  src/components/story/detail/sections/StoryDetailCommentSection.tsx
  src/components/story/detail/sections/StoryDetailContent.tsx
  src/components/story/detail/sections/StoryDetailMetaSection.tsx
  src/mocks/commentList.ts
  src/store/useCommentStore.ts
Labels: ✨ feature, 💄 design

#58 ♻️ Refactor: 홈 페이지 카드 컴포넌트로 변경
  src/app/page.tsx
  src/components/home/recipes/HomeSection.recipe.ts
  src/components/home/sections/ScrollMarkerSection.tsx
  src/components/home/sections/SubscribeTeaserSection.tsx
Labels: ♻️ refactor, 💄 design

#55 ✨ Feat: 스팟별 스토리 리스트 페이지 구현
  src/app/story/search/page.tsx
  src/components/story/StoryPlaceList.tsx
  src/components/ui/common/cards/SquareCard.tsx
  src/components/ui/common/cards/card.recipe.ts
  src/mocks/placeStoryList.ts
Labels: ✨ feature, 💄 design

#56 ✨ Feat: 스토리 작성 페이지 구현
  src/app/map/[id]/page.tsx
  src/app/story/post/page.tsx
  src/components/story/StoryPostForm.tsx
  src/components/story/sections/StoryPostPlace.tsx
  src/components/ui/common/dropdowns/FilterDropdown.tsx
  src/components/ui/common/dropdowns/dropdown.recipe.ts
  src/components/ui/common/modals/modal.recipe.ts
  src/lib/utils.ts
  src/mocks/searchPlace.ts
  src/util/date.ts
  tsconfig.json
Labels: ✨ feature, 💄 design

#60 ✨ Feat: 감정 아이콘 추가
  src/app/card/page.tsx
  src/components/icons/feelings/Angry.tsx
  src/components/icons/feelings/Frowning.tsx
  src/components/icons/feelings/Grinning.tsx
  src/components/icons/feelings/Neutral.tsx
  src/components/icons/feelings/Smiling.tsx
  src/components/icons/feelings/index.ts
  src/components/icons/iconProps.ts
  src/components/icons/index.ts
  src/components/story/StoryPlaceList.tsx
  src/components/story/StoryPostForm.tsx
  src/components/ui/common/cards/WideCardContent.tsx
  src/components/ui/common/dropdowns/FilterDropdown.tsx
  src/components/ui/feelings/FeelingIcon.tsx
  src/constants/story.ts
  src/mocks/placeStoryList.ts
Labels: ✨ feature, ♻️ refactor

#62 🐛 fix: 토글 컴포넌트 버그 수정
  src/components/ui/common/toggles/Like.tsx
  src/components/ui/common/toggles/Switch.tsx
Labels: 🐛 bugFix

#63 ✨ Feat: 챗봇 UI 및 대화 기능 완성
  src/app/layout.tsx
  src/components/chatBot/ChatBotHeader.tsx
  src/components/chatBot/ChatBotIntro.tsx
  src/components/chatBot/ChatBotMessage.tsx
  src/components/chatBot/ChatBotModal.tsx
  src/components/chatBot/ChatMessageList.tsx
  src/components/chatBot/chatBot.recipe.ts
  src/components/chatBot/types.ts
  src/components/icons/ui/ChatBotIcon.tsx
  src/components/icons/ui/index.ts
Labels: ✨ feature, 💄 design

#64 ✨ Feat: 지도 페이지 구현
  package-lock.json
  package.json
  public/images/markers/cafe.png
  public/images/markers/food.png
  public/images/markers/sight.png
  src/app/map/page.tsx
  src/components/icons/food/ForkSpoonIcon.tsx
  src/components/icons/location/MapLocationIcon.tsx
  src/components/map/MapSearch.tsx
  src/components/map/MapSearchBar.tsx
  src/components/map/MapView.tsx
  src/components/map/map.recipe.ts
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/maps/MarkerContainer.tsx
  src/components/ui/maps/MarkerIcon.tsx
  src/constants/map.ts
  src/mocks/mapDetail.ts
  src/util/map.ts
  tsconfig.json
Labels: ✨ feature, 💄 design

#70 🚀 Perf: 홈 페이지 코드 스플리팅 적용
  src/app/page.tsx
  src/components/home/sections/SearchStorySection.tsx
Labels: ♻️ refactor

#75 ✨ Feat: 챗봇 외부 클릭 시 자동 닫힘 기능 추가
  src/components/chatBot/ChatBotModal.tsx
Labels: ✨ feature

#81 🐛 Fix: 대문자 네이밍 누락된 constants 수정
  src/components/story/StoryPostForm.tsx
  src/components/ui/common/cards/WideCardContent.tsx
  src/components/ui/feelings/FeelingIcon.tsx
  src/constants/footer.ts
  src/constants/story.ts
Labels: 🐛 bugFix

#86 🎨 Style: 게시물 페이지 필요없는 로직 제거
  src/components/icons/ui/EyeIcons.tsx
  src/components/icons/ui/index.ts
  src/components/story/sections/StoryListSection.tsx
  src/components/story/sections/StorySearchSection.tsx
  src/components/ui/common/cards/StoryCard.tsx
  src/mocks/mockStoryList.ts
Labels: ✨ feature, 💄 design, :art: structure

#88 🎨 Style: 스토리상세 페이지 필요없는 구조 삭제 및 컴포넌트 삭제
  src/app/story/[storyId]/page.tsx
  src/components/story/detail/comment/CommentInputBox.tsx
  src/components/story/detail/sections/StoryDetailCommentSection.tsx
  src/components/story/detail/sections/StoryDetailContent.tsx
  src/components/story/detail/sections/StoryDetailMetaSection.tsx
Labels: ✨ feature, 🚚 remove / move, :art: structure

#90 💄 Design: 챗봇 반응형 개선
  src/components/chatBot/ChatBotHeader.tsx
  src/components/chatBot/ChatBotMessage.tsx
  src/components/chatBot/ChatBotModal.tsx
  src/components/chatBot/chatBot.recipe.ts
Labels: 💄 design

#94 ✨ Feat: 결제 페이지 구현
  src/app/payment/page.tsx
  src/app/subscribe/page.tsx
  src/components/icons/ui/KakaoIcon.tsx
  src/components/icons/ui/TossIcon.tsx
  src/components/icons/ui/index.ts
  src/components/ui/faq/FAQList.tsx
  src/constants/headerMenu.ts
  src/constants/subscribe.ts
Labels: ✨ feature, 💄 design

#95 ✨ Feat: 카카오 로그인 API 연동
  src/app/api/login/loginApi.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/users/login/kakao/callback/page.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/header.recipe.ts
  src/components/ui/common/loading/Spinner.tsx
  src/components/ui/common/loading/SpinnerMessage.tsx
  src/components/ui/common/loading/spinner.recipe.ts
  src/constants/auth.ts
  src/constants/headerMenu.ts
  src/hooks/useIsMobile.ts
  src/providers/AuthInitializer.tsx
  src/providers/GlobalAuthGuard.tsx
  src/store/useAuthStore.ts
Labels: 🔌 api, ✨ feature

#100 ✨ Feat: Ai 챗봇 Api 연결
  src/api/endpoints.ts
  src/api/instance.ts
  src/api/options/chateBot.ts
  src/components/chatBot/ChatBotMessage.tsx
  src/components/chatBot/ChatMessageList.tsx
  src/components/chatBot/chatBot.recipe.ts
  src/components/chatBot/types.ts
Labels: 🔌 api, ✨ feature, :art: structure

#101 :truck: rename: #99 mutation.ts 파일 이름 수정 함수 이름 수정
  src/api/options/chatBotOption.ts
  src/components/chatBot/ChatBotMessage.tsx
Labels: 🚚 remove / move

#107 ✨ Feat: story 작성 api 연결
  src/api/options/markerOption.ts
  src/api/options/storyOption.ts
  src/components/story/StoryPostForm.tsx
  src/components/story/sections/StoryPostPlace.tsx
  src/components/ui/common/dropdowns/FilterDropdown.tsx
  src/mocks/searchPlace.ts
  src/types/index.ts
  src/types/story.ts
Labels: 🔌 api, ✨ feature

#108 ✨ Feat: story 작성 페이지 내 장소 검색 api 연결
  src/api/options/markerOption.ts
  src/components/story/StoryPostForm.tsx
  src/components/story/sections/StoryPostPlace.tsx
  src/components/story/sections/story.recipe.ts
  src/components/ui/common/modals/modal.recipe.ts
  src/hooks/useDebounce.ts
  src/types/marker.ts
Labels: 🐛 bugFix, ✨ feature, 💄 design

#109 ✨ Feat: 마이페이지 메인 페이지 구현
  next.config.mjs
  src/api/interceptor.ts
  src/app/api/user/userApi.ts
  src/app/mypage/page.tsx
  src/app/users/login/kakao/callback/page.tsx
  src/components/icons/IconWrapper.tsx
  src/components/layouts/Header.tsx
  src/components/mypage/MypageMenuList.tsx
  src/components/mypage/MypageProfile.tsx
  src/components/mypage/MypageStats.tsx
  src/components/mypage/mypage.recipe.ts
  src/constants/headerMenu.ts
  src/hooks/useUserProfile.ts
  src/store/useAuthStore.ts
  src/types/user.ts
Labels: 🔌 api, ✨ feature, 💄 design, 🔧 chore, :art: structure

#119 ♻️ Refactor: 스토리 이미지 엔드포인트 수정 반영
  src/api/endpoints.ts
  src/api/options/storyOption.ts
Labels: 🔌 api, ♻️ refactor

#118 Feat: 마커 상세 페이지 API 연결
  src/api/endpoints.ts
  src/api/options/markerOption.ts
  src/api/options/storyOption.ts
  src/app/map/[id]/page.tsx
  src/components/map/MapDetailStory.tsx
  src/components/map/MapResults.tsx
  src/components/map/MapTabs.tsx
  src/types/marker.ts
  src/types/story.ts
Labels: 🔌 api, ✨ feature

#122 ✨ Feat: 구글 로그인 API 연동
  src/app/api/login/loginApi.ts
  src/app/login/page.tsx
  src/app/users/login/google/callback/page.tsx
  src/constants/auth.ts
Labels: 🔌 api, ✨ feature

#123 ♻️ Refactor: 마커별 스토리에서 이미지 컴포넌트 분리
  src/components/map/MapDetailStory.tsx
  src/components/map/MapDetailStoryImages.tsx
Labels: ♻️ refactor

#124 🐛 Fix: 이미지 해상도 깨짐 현상 수정
  src/components/map/MapDetailStoryImages.tsx
Labels: 🐛 bugFix

#127 ✨ Feat: 스팟별 스토리 리스트 API 연결
  src/app/map/[id]/page.tsx
  src/components/map/MapDetailStory.tsx
  src/components/map/MapDetailStoryImages.tsx
  src/components/map/MapView.tsx
  src/components/story/StoryPlaceList.tsx
  src/components/story/sections/StoryPostPlace.tsx
  src/components/ui/common/cards/WideCardContent.tsx
  src/mocks/placeStoryList.ts
  src/util/date.ts
Labels: 🔌 api, ✨ feature

#132 🔥 Remove: 스토리 post 중복 파일 삭제
  src/components/story/sections/StoryPostForm.tsx
Labels: 🚚 remove / move

#141 ✨ Feat: 위치 기반 검색 기능 추가
  public/images/markers/current.png
  src/components/map/MapView.tsx
  src/components/map/SearchBar.tsx
  src/components/ui/maps/MarkerContainer.tsx
Labels: 🔌 api, ✨ feature

#144 ✨ Feat: 작성 스토리 수정 API 연결
  src/api/options/markerOption.ts
  src/api/options/storyOption.ts
  src/app/map/[id]/page.tsx
  src/app/story/post/[storyId]/page.tsx
  src/components/map/MapDetailStory.tsx
  src/components/map/MapDetailStoryImages.tsx
  src/components/story/StoryPlaceList.tsx
  src/components/story/StoryPostForm.tsx
  src/components/story/detail/StoryContentActions.tsx
  src/components/story/detail/StoryDetailContent.tsx
  src/components/story/sections/StoryPostPlace.tsx
  src/components/ui/common/cards/SquareCard.tsx
  src/components/ui/common/modals/Modal.tsx
  src/components/ui/common/pageHeader/pageHeader.recipe.ts
  src/types/story.ts
  src/util/date.ts
Labels: 🔌 api, ✨ feature

#153 ✨ Feat: 팔로우 추가 API 연결
  src/api/options/followsOption.ts
  src/components/story/detail/StoryContentActions.tsx
  src/components/story/detail/UserInfo.tsx
  src/components/ui/common/cards/StoryCard.tsx
Labels: 🔌 api, ✨ feature

#157 💄 Design: 게시판 ui 수정
  src/app/story/[storyId]/page.tsx
  src/components/story/detail/StoryDetailContent.tsx
  src/components/story/detail/StoryDetailSkeleton.tsx
Labels: ✨ feature, 💄 design

#160 ✨ Feat: 팔로우 API를 연결
  src/api/endpoints.ts
  src/api/options/followsOption.ts
  src/app/user/_components/UserPageContent.tsx
  src/components/story/detail/StoryContentActions.tsx
  src/hooks/useFollowStatus.ts
Labels: 🔌 api, ✨ feature, ♻️ refactor

#163 ✨ Feat: 마커 리스트 정렬 기능 구현
  src/components/map/MapResults.tsx
  src/components/map/MapTabs.tsx
Labels: 🔌 api, ✨ feature

#164 ✨ Feat: 챗봇 요약 API 연결
  src/api/options/chatBotOption.ts
  src/components/chatBot/ChatBotIntro.tsx
  src/components/chatBot/ChatBotMessage.tsx
  src/components/chatBot/chatBot.recipe.ts
Labels: 🔌 api, ✨ feature, 💄 design

#171 ✨ Feat: 시스템 모드 설정 기능 구현
  panda.config.ts
  src/app/layout.tsx
  src/app/mypage/settings/ThemeToggle.tsx
  src/app/mypage/settings/page.tsx
  src/components/layouts/Header.tsx
  src/providers/ThemeInitializer.tsx
  src/store/useThemeStore.ts
Labels: ✨ feature, 💄 design

#172 ✨ Feat: 알림 API 연결
  src/api/endpoints.ts
  src/api/options/notificationOption.ts
  src/app/payment/page.tsx
  src/types/notification.ts
Labels: 🔌 api, ✨ feature, ♻️ refactor

#178 🐛 Fix: 알림 엔드포인트 주소 수정 (alert API endpoint update)
  src/api/endpoints.ts
Labels: 🐛 bugFix

#182 ✨ Feat: 결제 이력 API 연결
  src/api/endpoints.ts
  src/api/options/paymentOption.ts
  src/app/mypage/payment-history/_components/PaymentList.tsx
  src/app/mypage/payment-history/layout.tsx
  src/app/mypage/payment-history/page.tsx
  src/components/icons/ui/PaymentIcon.tsx
  src/components/icons/ui/index.ts
  src/components/mypage/MypageMenuList.tsx
  src/components/mypage/mypage.recipe.ts
  src/components/ui/common/modals/Modal.tsx
  src/types/payment.types.ts
Labels: 🔌 api, ✨ feature, ♻️ refactor, 💄 design

#188 ✨ Feat: 구독, 결제 SEO 추가
  src/app/payment/_components/PaymentSection.tsx
  src/app/payment/page.tsx
  src/app/subscribe/page.tsx
  src/components/chatBot/ChatBotIntro.tsx
  src/components/ui/faq/FAQList.tsx
Labels: ✨ feature, 🚀 performance

#191 ✨ Feat: 구독 API 연결
  src/api/endpoints.ts
  src/api/options/paymentOption.ts
  src/app/mypage/page.tsx
  src/app/mypage/subscribe/_components/SubscribeList.tsx
  src/app/mypage/subscribe/page.tsx
  src/components/mypage/MypageMenuList.tsx
  src/components/mypage/WithdrawalConfirmModal.tsx
  src/types/subscribeId.type.ts
Labels: 🔌 api, ✨ feature, ♻️ refactor, 💄 design, :art: structure

#138 ✨ Feat: 마커 좋아요 API 연결
  src/api/options/markerOption.ts
  src/components/map/MapResults.tsx
  src/components/map/MapTabs.tsx
  src/components/map/MapView.tsx
  src/components/ui/common/cards/SquareCard.tsx
Labels: 🔌 api, ✨ feature

#193 🐛 Fix: story post 완료 시 라우팅 경로 응답값 이용하도록 수정
  src/components/story/StoryPostForm.tsx
Labels: 🐛 bugFix

#197 🚚 Remove: 개발 서버에서 필요한 페이지를 배포하여 삭제함
  src/app/card/page.tsx
  src/app/icon-preview/page.tsx
  src/app/testPage/page.tsx
Labels: 🚚 rename / move

#189 ✨ Feat: 경로 API 연결
  src/api/endpoints.ts
  src/api/options/markerOption.ts
  src/api/options/routeOption.ts
  src/app/map/[id]/page.tsx
  src/components/map/MapResults.tsx
  src/components/map/MapTabs.tsx
  src/components/map/MapView.tsx
  src/components/map/RouteList.tsx
  src/components/map/map.recipe.ts
  src/components/story/StoryPlaceList.tsx
  src/components/story/detail/StoryContentActions.tsx
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/common/modals/Modal.tsx
  src/components/ui/common/modals/modal.recipe.ts
  src/components/ui/maps/MarkerContainer.tsx
  src/components/ui/maps/RouteCreateModal.tsx
  src/components/ui/maps/RouteMarkModal.tsx
  src/store/useModalStore.ts
  src/types/route.ts
Labels: 🔌 api, ✨ feature

#202 ✨ Feat: 토스트 라이브러리 설치 및 알림 연결
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/payment-history/page.tsx
  src/app/mypage/subscribe/page.tsx
  src/app/payment/_components/PaymentSection.tsx
  src/app/users/login/kakao/callback/page.tsx
  src/components/mypage/MypageProfile.tsx
  src/components/mypage/WithdrawalConfirmModal.tsx
  src/components/story/StoryPostForm.tsx
  src/components/story/detail/StoryContentActions.tsx
  src/components/story/detail/comment/CommentForm.tsx
Labels: ✨ feature

#207 ✨ Feat: 루트 에러 바운더리 적용
  src/app/error.tsx
Labels: ✨ feature, 💄 design

#210 ✨ Feat: 지도 에러처리 추가
  src/components/map/MapView.tsx
  src/components/story/detail/StoryContentActions.tsx
  src/components/ui/common/cards/card.recipe.ts
  src/components/ui/common/modals/Modal.tsx
  src/components/ui/maps/RouteCreateModal.tsx
  src/components/ui/maps/RouteMarkModal.tsx
Labels: 🐛 bugFix, ✨ feature

#216 🚚 remove: 마이페이지 내 게시 및 팔로우 현황 영역 삭제
  src/app/mypage/page.tsx
  src/components/mypage/MypageStats.tsx
  src/components/mypage/mypage.recipe.ts
Labels: 🚚 rename / move
